export const ENEMIES: Record<string, { name: string; expReward: number; goldReward: number; isElite?: boolean; isBoss?: boolean }> = {
  forest_wolf: { name: "Forest Wolf", expReward: 15, goldReward: 5 },
  goblin_scout: { name: "Goblin Scout", expReward: 18, goldReward: 8 },
  giant_spider: { name: "Giant Spider", expReward: 22, goldReward: 10 },
  wild_boar: { name: "Wild Boar", expReward: 17, goldReward: 6 },
  moss_golem: { name: "Moss Golem", expReward: 20, goldReward: 8 },
  vine_serpent: { name: "Vine Serpent", expReward: 24, goldReward: 10 },
  forest_bandit: { name: "Forest Bandit", expReward: 26, goldReward: 14 },
  poison_frog: { name: "Poison Frog", expReward: 16, goldReward: 6 },
  bark_spider: { name: "Bark Spider", expReward: 20, goldReward: 8 },
  goblin_shaman: { name: "Goblin Shaman", expReward: 25, goldReward: 12 },
  treant_sprout: { name: "Treant Sprout", expReward: 18, goldReward: 7 },
  thornback_boar: { name: "Thornback Boar", expReward: 19, goldReward: 8 },
  ancient_treant: { name: "Ancient Treant", expReward: 300, goldReward: 150, isElite: true },
  forest_troll: { name: "Forest Troll", expReward: 350, goldReward: 175, isElite: true },
  forest_guardian: { name: "Forest Guardian", expReward: 150, goldReward: 80, isBoss: true },
  sand_scorpion: { name: "Sand Scorpion", expReward: 35, goldReward: 15 },
  desert_bandit: { name: "Desert Bandit", expReward: 40, goldReward: 20 },
  sand_golem: { name: "Sand Golem", expReward: 45, goldReward: 22 },
  fire_lizard: { name: "Fire Lizard", expReward: 42, goldReward: 18 },
  cactus_wraith: { name: "Cactus Wraith", expReward: 38, goldReward: 16 },
  dune_raider: { name: "Dune Raider", expReward: 50, goldReward: 25 },
  tomb_scarab: { name: "Tomb Scarab", expReward: 36, goldReward: 17 },
  sandstorm_elemental: { name: "Sandstorm Elemental", expReward: 55, goldReward: 28 },
  desert_cobra: { name: "Desert Cobra", expReward: 40, goldReward: 19 },
  mummy_warrior: { name: "Mummy Warrior", expReward: 42, goldReward: 20 },
  sand_phantom: { name: "Sand Phantom", expReward: 48, goldReward: 24 },
  flame_jackal: { name: "Flame Jackal", expReward: 46, goldReward: 22 },
  tomb_guardian: { name: "Tomb Guardian", expReward: 52, goldReward: 26 },
  sand_titan: { name: "Sand Titan", expReward: 600, goldReward: 300, isElite: true },
  fire_colossus: { name: "Fire Colossus", expReward: 700, goldReward: 350, isElite: true },
  desert_wyrm: { name: "Desert Wyrm", expReward: 400, goldReward: 200, isBoss: true },
  frost_wolf: { name: "Frost Wolf", expReward: 70, goldReward: 30 },
  ice_elemental: { name: "Ice Elemental", expReward: 85, goldReward: 40 },
  yeti: { name: "Yeti", expReward: 100, goldReward: 50 },
  glacial_golem: { name: "Glacial Golem", expReward: 95, goldReward: 45 },
  snow_harpy: { name: "Snow Harpy", expReward: 90, goldReward: 42 },
  frozen_knight: { name: "Frozen Knight", expReward: 105, goldReward: 52 },
  ice_witch: { name: "Ice Witch", expReward: 110, goldReward: 55 },
  blizzard_sprite: { name: "Blizzard Sprite", expReward: 80, goldReward: 38 },
  frost_troll: { name: "Frost Troll", expReward: 85, goldReward: 40 },
  avalanche_wraith: { name: "Avalanche Wraith", expReward: 92, goldReward: 44 },
  ice_basilisk: { name: "Ice Basilisk", expReward: 98, goldReward: 48 },
  polar_bear_spirit: { name: "Polar Bear Spirit", expReward: 105, goldReward: 52 },
  crystal_golem: { name: "Crystal Golem", expReward: 108, goldReward: 54 },
  frost_colossus: { name: "Frost Colossus", expReward: 1200, goldReward: 600, isElite: true },
  blizzard_titan: { name: "Blizzard Titan", expReward: 1400, goldReward: 700, isElite: true },
  frost_dragon: { name: "Frost Dragon", expReward: 1000, goldReward: 500, isBoss: true },
  shadow_wraith: { name: "Shadow Wraith", expReward: 150, goldReward: 70 },
  demon_knight: { name: "Demon Knight", expReward: 200, goldReward: 90 },
  void_walker: { name: "Void Walker", expReward: 180, goldReward: 85 },
  soul_harvester: { name: "Soul Harvester", expReward: 190, goldReward: 88 },
  nightmare_hound: { name: "Nightmare Hound", expReward: 185, goldReward: 82 },
  cursed_revenant: { name: "Cursed Revenant", expReward: 205, goldReward: 95 },
  dark_sorcerer: { name: "Dark Sorcerer", expReward: 210, goldReward: 100 },
  abyssal_fiend: { name: "Abyssal Fiend", expReward: 220, goldReward: 105 },
  blood_shade: { name: "Blood Shade", expReward: 195, goldReward: 90 },
  necrotic_golem: { name: "Necrotic Golem", expReward: 210, goldReward: 98 },
  void_assassin: { name: "Void Assassin", expReward: 215, goldReward: 105 },
  rift_stalker: { name: "Rift Stalker", expReward: 220, goldReward: 108 },
  shadow_dragon: { name: "Shadow Dragon", expReward: 230, goldReward: 112 },
  void_titan: { name: "Void Titan", expReward: 3000, goldReward: 1500, isElite: true },
  blood_colossus: { name: "Blood Colossus", expReward: 3500, goldReward: 1800, isElite: true },
  shadow_lord: { name: "Shadow Lord", expReward: 3000, goldReward: 1500, isBoss: true },
  celestial_guardian: { name: "Celestial Guardian", expReward: 350, goldReward: 150 },
  seraph_warrior: { name: "Seraph Warrior", expReward: 400, goldReward: 180 },
  titan: { name: "Titan", expReward: 500, goldReward: 250 },
  star_phantom: { name: "Star Phantom", expReward: 380, goldReward: 170 },
  nova_knight: { name: "Nova Knight", expReward: 430, goldReward: 200 },
  divine_construct: { name: "Divine Construct", expReward: 460, goldReward: 210 },
  astral_wyrm: { name: "Astral Wyrm", expReward: 490, goldReward: 230 },
  cosmic_sentinel: { name: "Cosmic Sentinel", expReward: 520, goldReward: 240 },
  light_golem: { name: "Light Golem", expReward: 370, goldReward: 160 },
  empyrean_shade: { name: "Empyrean Shade", expReward: 410, goldReward: 185 },
  starfire_drake: { name: "Starfire Drake", expReward: 460, goldReward: 215 },
  void_seraph: { name: "Void Seraph", expReward: 480, goldReward: 225 },
  genesis_elemental: { name: "Genesis Elemental", expReward: 510, goldReward: 240 },
  celestial_titan: { name: "Celestial Titan", expReward: 12000, goldReward: 6000, isElite: true },
  omega_seraph: { name: "Omega Seraph", expReward: 14000, goldReward: 7000, isElite: true },
  cosmic_overlord: { name: "Cosmic Overlord", expReward: 10000, goldReward: 5000, isBoss: true },
};

export function calculateExpToLevel(level: number): number {
  return Math.floor(100 * Math.pow(1.15, level - 1));
}
